#!/bin/bash
# Script to generate release notes and create release tag

set -e

RELEASE_VERSION="$1"
GITHUB_TOKEN="$2"
REPO_URL="${3:-https://github.com/alejandramantillac/ecommerce-microservice-backend-app.git}"

if [ -z "$RELEASE_VERSION" ] || [ -z "$GITHUB_TOKEN" ]; then
    echo "Usage: $0 <release-version> <github-token> [repo-url]"
    exit 1
fi

echo "========================================="
echo "Generating Release Notes"
echo "Version: ${RELEASE_VERSION}"
echo "========================================="

# Configure git
git config --global user.name "Jenkins CI"
git config --global user.email "jenkins@example.com"

# Generate changelog
echo "Generating changelog..."
git log --oneline --since="7 days ago" > CHANGELOG.md

# Create release notes
echo "Creating release notes..."
cat > release_notes.md << EOF
# Release ${RELEASE_VERSION}

**Date:** $(date)

**Environment:** Production

## Changes

$(cat CHANGELOG.md)

## Deployed Services

- user-service
- product-service
- order-service
- shipping-service
- service-discovery
- api-gateway
- proxy-client

## Testing Summary

All tests passed successfully:
- ✓ Unit Tests
- ✓ Integration Tests
- ✓ End-to-End Tests
- ✓ Performance Tests

## Deployment Details

- Image Tag: ${IMAGE_TAG:-latest}
- Namespace: ${K8S_NAMESPACE_PROD:-prod}
- Registry: ${REGISTRY:-docker.io/alejandramantillac}

---
Generated by Jenkins CI on $(date)
EOF

echo ""
echo "Release Notes:"
echo "----------------------------------------"
cat release_notes.md
echo "----------------------------------------"
echo ""

# Create and push tag
echo "Creating release tag v${RELEASE_VERSION}..."
git tag -a "v${RELEASE_VERSION}" -m "Release version ${RELEASE_VERSION}"

echo "Pushing tag to remote repository..."
git remote set-url origin "https://${GITHUB_TOKEN}@${REPO_URL#https://}"
git push origin "v${RELEASE_VERSION}"

echo ""
echo "✓ Release notes generated and tag pushed successfully"
echo "  Tag: v${RELEASE_VERSION}"
echo "  Notes: release_notes.md"

