#!/bin/bash
# Script para crear Grafana manualmente con Azure CLI cuando Terraform no soporta la versión requerida
# Usage: ./jenkins/scripts/setup-grafana-manual.sh <resource-group> <grafana-name> <location> <sku> <monitor-workspace-id>

set -e

RESOURCE_GROUP="${1}"
GRAFANA_NAME="${2}"
LOCATION="${3}"
SKU="${4:-Essential}"
MONITOR_WORKSPACE_ID="${5}"

if [ -z "$RESOURCE_GROUP" ] || [ -z "$GRAFANA_NAME" ] || [ -z "$LOCATION" ]; then
    echo "Usage: $0 <resource-group> <grafana-name> <location> [sku] [monitor-workspace-id]"
    echo "Example: $0 ecommerce-staging-rg ecom-stg-grafana eastus2 Essential"
    exit 1
fi

echo "========================================="
echo "Creating Azure Managed Grafana"
echo "========================================="
echo "Resource Group: ${RESOURCE_GROUP}"
echo "Grafana Name: ${GRAFANA_NAME}"
echo "Location: ${LOCATION}"
echo "SKU: ${SKU}"
echo "========================================="

# Nota: Azure CLI no soporta crear Grafana con SKU Essential, solo Standard
# Por lo tanto, usamos la API REST de Azure directamente
echo "Using Azure REST API to create Grafana (CLI doesn't support Essential SKU)"

# Verificar si Grafana ya existe usando REST API
SUBSCRIPTION_ID=$(az account show --query id -o tsv)
GRAFANA_RESOURCE_ID="/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Dashboard/grafana/${GRAFANA_NAME}"

if az rest --method GET \
    --url "https://management.azure.com${GRAFANA_RESOURCE_ID}?api-version=2023-09-01" \
    --output none 2>/dev/null; then
    echo "Grafana '${GRAFANA_NAME}' already exists, skipping creation"
    exit 0
fi

# Crear Grafana usando Azure REST API directamente
# Azure CLI no soporta crear Grafana con SKU Essential, así que usamos REST API
echo "Creating Grafana with Azure REST API (CLI doesn't support Essential SKU)..."

# Preparar el body JSON para la API REST
GRAFANA_BODY=$(cat <<EOF
{
  "location": "${LOCATION}",
  "sku": {
    "name": "${SKU}"
  },
  "properties": {
    "grafanaMajorVersion": "11",
    "publicNetworkAccess": "Enabled",
    "apiKey": "Enabled",
    "deterministicOutboundIP": "Disabled",
    "zoneRedundancy": "Disabled",
    "autoGeneratedDomainNameLabelScope": "TenantReuse"
  },
  "identity": {
    "type": "SystemAssigned"
  }
}
EOF
)

# Crear Grafana usando REST API
echo "Calling Azure REST API to create Grafana..."
if ! az rest --method PUT \
    --url "https://management.azure.com${GRAFANA_RESOURCE_ID}?api-version=2023-09-01" \
    --headers "Content-Type=application/json" \
    --body "$GRAFANA_BODY" >/dev/null 2>&1; then
    echo "Error: Failed to create Grafana via REST API"
    echo "Response:"
    az rest --method PUT \
        --url "https://management.azure.com${GRAFANA_RESOURCE_ID}?api-version=2023-09-01" \
        --headers "Content-Type=application/json" \
        --body "$GRAFANA_BODY" 2>&1 || true
    exit 1
fi

echo "✓ Grafana creation initiated via REST API"

# Esperar a que Grafana esté disponible (puede tomar unos minutos)
echo "Waiting for Grafana to be provisioned (this may take 2-5 minutes)..."
MAX_RETRIES=30
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    PROVISIONING_STATE=$(az rest --method GET \
        --url "https://management.azure.com${GRAFANA_RESOURCE_ID}?api-version=2023-09-01" \
        --query "properties.provisioningState" -o tsv 2>/dev/null || echo "Unknown")
    
    if [ "$PROVISIONING_STATE" = "Succeeded" ]; then
        echo "✓ Grafana is ready (provisioning state: $PROVISIONING_STATE)"
        break
    elif [ "$PROVISIONING_STATE" = "Failed" ]; then
        echo "Error: Grafana provisioning failed"
        exit 1
    fi
    
    if [ $((RETRY_COUNT % 3)) -eq 0 ]; then
        echo "Grafana provisioning state: ${PROVISIONING_STATE:-Creating...} (${RETRY_COUNT}/${MAX_RETRIES} checks)"
    fi
    
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 10
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    FINAL_STATE=$(az rest --method GET \
        --url "https://management.azure.com${GRAFANA_RESOURCE_ID}?api-version=2023-09-01" \
        --query "properties.provisioningState" -o tsv 2>/dev/null || echo "Unknown")
    if [ "$FINAL_STATE" != "Succeeded" ]; then
        echo "Warning: Grafana creation may still be in progress (state: $FINAL_STATE). Continuing anyway..."
    fi
fi

echo "✓ Grafana created successfully"

# Habilitar API keys después de la creación (opcional, Terraform lo configurará)
echo "Attempting to enable API keys (this may not be supported in all CLI versions)..."
az grafana api-key enable \
    --name "$GRAFANA_NAME" \
    --resource-group "$RESOURCE_GROUP" 2>/dev/null || \
az grafana update \
    --name "$GRAFANA_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --api-key Enabled 2>/dev/null || \
echo "Note: API keys will be configured by Terraform after import"

# Si se proporciona el Monitor Workspace ID, integrarlo usando REST API
if [ -n "$MONITOR_WORKSPACE_ID" ]; then
    echo "Integrating with Azure Monitor Workspace..."
    INTEGRATION_BODY=$(cat <<EOF
{
  "azureMonitorWorkspaceIntegrations": [
    {
      "azureMonitorWorkspaceResourceId": "${MONITOR_WORKSPACE_ID}"
    }
  ]
}
EOF
)
    # Intentar agregar la integración (puede fallar si ya existe, pero no es crítico)
    az rest --method PATCH \
        --url "https://management.azure.com${GRAFANA_RESOURCE_ID}?api-version=2023-09-01" \
        --headers "Content-Type=application/json" \
        --body "$INTEGRATION_BODY" >/dev/null 2>&1 || echo "Note: Monitor workspace integration will be handled by Terraform after import"
fi

echo ""
echo "========================================="
echo "Grafana setup completed!"
echo "========================================="
echo "To import to Terraform, run:"
echo "terraform import module.monitoring.azurerm_dashboard_grafana.grafana \\"
echo "  /subscriptions/SUBSCRIPTION_ID/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Dashboard/grafana/${GRAFANA_NAME}"
echo ""

