# ConfigMap for Staging Environment
# Apply: kubectl apply -f k8s/02-configmap-staging.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-config
  namespace: staging
  labels:
    environment: staging
    managed-by: jenkins
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: "dev"
  
  # JVM Options - Staging tiene más recursos
  JAVA_OPTS: "-Xms384m -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError"
  
  # Service Discovery (Eureka)
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://service-discovery.staging.svc.cluster.local:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_INSTANCE_HOSTNAME: "${spring.application.name}.staging.svc.cluster.local"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  
  # Zipkin Tracing
  SPRING_ZIPKIN_BASE_URL: "http://zipkin.staging.svc.cluster.local:9411/"
  SPRING_SLEUTH_SAMPLER_PROBABILITY: "0.5"  # 50% sampling para staging
  
  # Service URLs (Internal Communication)
  USER_SERVICE_HOST: "http://user-service.staging.svc.cluster.local:8700"
  PRODUCT_SERVICE_HOST: "http://product-service.staging.svc.cluster.local:8500"
  FAVOURITE_SERVICE_HOST: "http://favourite-service.staging.svc.cluster.local:8400"
  PROXY_CLIENT_HOST: "http://proxy-client.staging.svc.cluster.local:8900"
  API_GATEWAY_HOST: "http://api-gateway.staging.svc.cluster.local:8080"
  
  # Logging
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_SELIMHORRI: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  
  # Management & Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  
  # Resilience
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DEFAULT_SLIDING_WINDOW_SIZE: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DEFAULT_FAILURE_RATE_THRESHOLD: "50"