# Zipkin Tracing Service
# Uses public Docker image from openzipkin/zipkin

apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: ${NAMESPACE}
  labels:
    app: zipkin
    component: monitoring
spec:
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: ${NODE_PORT}
      name: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: ${NAMESPACE}
  labels:
    app: zipkin
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
              name: http
          env:
            - name: STORAGE_TYPE
              value: mem
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3