#!/usr/bin/env bash
set -euo pipefail

COMMIT_MSG_FILE="$1"
MESSAGE="$(<"$COMMIT_MSG_FILE")"

# Allow autogenerated merge commits
if [[ "$MESSAGE" =~ ^Merge\ .* ]]; then
  exit 0
fi

PATTERN='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([\w\-.]+\))?(!)?: .+'

if [[ ! "$MESSAGE" =~ $PATTERN ]]; then
  cat <<'EOF'
❌ Commit message does not follow Conventional Commits.
Expected format: <type>(<scope>): <summary>
Allowed types: feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert
Example: feat(user-service): add profile endpoint
EOF
  exit 1
fi

exit 0

